const NEG='blurry, low quality, chaotic, deformed, watermark, bad anatomy, shaky camera';
const MIN=20;

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
function hfBase(env){const id=env.HF_SPACE||'Saravutw/WAN2.2_I2V_LIGHTNING_4-8step_custom';const p=id.split('/');return 'https://'+p[0].toLowerCase()+'-'+p[1].toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.hf.space'}
function auth(env){return env.HF_TOKEN?{Authorization:'Bearer '+env.HF_TOKEN}:{}}

async function upload(file,env){const fd=new FormData();fd.append('files',file,file.name||'input.png');const r=await fetch(hfBase(env)+'/gradio_api/upload',{method:'POST',headers:auth(env),body:fd});const t=await r.text();if(!r.ok)throw Error('Hugging Face upload failed ('+r.status+'): '+t.slice(0,700));let x;try{x=JSON.parse(t)}catch{throw Error('Hugging Face returned invalid upload data: '+t.slice(0,300))}const path=Array.isArray(x)?x[0]:x;if(!path)throw Error('Hugging Face returned no uploaded file path');return{path,meta:{_type:'gradio.FileData'},orig_name:file.name||'input.png'}}
async function startVideo(req,env){try{const fd=await req.formData();const image=fd.get('image');if(!(image instanceof File))return json({error:'Please choose a starting image.'},400);const prompt=String(fd.get('prompt')||'high quality, high resolution, cinematic motion, smooth animation');const duration=Number(fd.get('duration')||3.5);if(!Number.isFinite(duration)||duration<2||duration>12)return json({error:'Invalid video duration.'},400);const input=await upload(image,env);const data=[input,null,prompt,4,NEG,duration,1,1,42,true,5,'UniPCMultistep',3,16,false,true];const r=await fetch(hfBase(env)+'/gradio_api/call/generate_video',{method:'POST',headers:{...auth(env),'content-type':'application/json'},body:JSON.stringify({data})});const t=await r.text();if(!r.ok)throw Error('Wan request failed ('+r.status+'): '+t.slice(0,800));let x;try{x=JSON.parse(t)}catch{throw Error('Wan returned invalid JSON: '+t.slice(0,500))}if(!x?.event_id)throw Error('Wan returned no event id: '+t.slice(0,700));return json({ok:true,eventId:x.event_id})}catch(e){return json({ok:false,error:e?.message||String(e)},502)}}
async function streamVideo(id,env){if(!id)return json({error:'Missing eventId'},400);const r=await fetch(hfBase(env)+'/gradio_api/call/generate_video/'+encodeURIComponent(id),{headers:auth(env)});if(!r.ok)return new Response(await r.text(),{status:r.status,headers:{'content-type':'text/plain;charset=utf-8'}});return new Response(r.body,{headers:{'content-type':'text/event-stream;charset=utf-8','cache-control':'no-cache,no-store','connection':'keep-alive'}})}
async function videoFile(req,env){const raw=new URL(req.url).searchParams.get('path');if(!raw)return json({error:'Missing video path'},400);let p;try{p=decodeURIComponent(raw)}catch{p=raw}let target;if(p.startsWith('https://')){if(new URL(p).host!==new URL(hfBase(env)).host)return json({error:'Invalid video host'},400);target=p}else if(p.startsWith('/gradio_api/file=')){target=hfBase(env)+p}else{return json({error:'Invalid video path'},400)}const r=await fetch(target,{headers:auth(env)});if(!r.ok)return new Response(await r.text(),{status:r.status,headers:{'content-type':'text/plain;charset=utf-8'}});const h=new Headers(r.headers);h.set('content-disposition','inline');h.set('cache-control','no-store');if(!h.get('content-type')||h.get('content-type')==='application/octet-stream')h.set('content-type','video/mp4');return new Response(r.body,{status:r.status,headers:h})}

const HTML=String.raw`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Video Script Studio</title><style>
body{font-family:system-ui;margin:0;background:#0b1020;color:#eef2ff}main{max-width:1050px;margin:auto;padding:30px 20px}h1{margin:0 0 8px}.muted{color:#aeb9d6}.version{font-size:12px;color:#7f8eb5;margin:8px 0 18px}.card{background:#131b31;border:1px solid #273454;border-radius:16px;padding:20px;margin:18px 0}label{display:block;font-weight:700;margin:0 0 8px}textarea,input,select{width:100%;box-sizing:border-box;background:#0d1427;color:white;border:1px solid #344262;border-radius:10px;padding:12px;font:inherit}textarea{min-height:160px}.row,.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.btn{background:#6d5dfc;color:white;border:0;border-radius:10px;padding:12px 18px;font-weight:800;cursor:pointer}.btn:disabled{opacity:.42;cursor:not-allowed}.status{margin-top:12px;padding:12px;background:#0d1427;border-radius:10px}.bad{color:#ff6975;font-weight:800}.good{color:#72e6a3;font-weight:800}.scene{border:1px solid #344262;border-radius:12px;padding:14px;margin:12px 0;background:#0d1427}.scene textarea{min-height:90px}.sceneHead{display:flex;justify-content:space-between}.badge{border:1px solid #47577d;border-radius:999px;padding:4px 9px;font-size:12px}.video{max-width:100%;margin-top:15px;display:block}.download{display:inline-block;margin-top:10px;background:#245c46;color:white;text-decoration:none;padding:10px 14px;border-radius:9px;font-weight:800}.small{font-size:12px;color:#9eabd0}@media(max-width:700px){.row,.grid{grid-template-columns:1fr}}
</style></head><body><main>
<h1>AI Video Script Studio</h1><div class="muted">Script → scene development → scene-by-scene Wan 2.2 image-to-video</div><div class="version">Framework v24 • persistent script state • sequential scene generation • robust Wan stream handling</div>
<div class="card"><label for="script">1. Your script</label><textarea id="script" placeholder="Paste your complete story or script here."></textarea><div id="count" class="status bad">0 words — 20 required</div><div id="validation" class="status bad">Please enter at least 20 words before developing scenes.</div><div class="row" style="margin-top:14px"><div><label for="pace">Narration pace</label><select id="pace"><option value="130">Slow / cinematic — 130 words/min</option><option value="150" selected>Normal narration — 150 words/min</option><option value="170">Fast narration — 170 words/min</option></select></div><div><label for="minDuration">Minimum scene duration</label><input id="minDuration" type="number" min="2" max="10" step="0.5" value="3"></div></div><p class="muted">Your script is saved automatically in this browser. Refreshing the page will restore it and rebuild the scenes.</p><button id="develop" type="button" class="btn" disabled>Develop Scenes</button><div id="devStatus" class="status">Type at least 20 words.</div></div>
<div id="sceneCard" class="card" style="display:none"><b>2. Developed scenes</b><div id="summary" class="muted" style="margin-top:5px"></div><div id="scenes"></div></div>
<div class="card"><label for="quickImage">3. Quick Wan 2.2 scene test</label><input id="quickImage" type="file" accept="image/*"><div id="quickImageStatus" class="status">No image selected.</div><label style="margin-top:12px" for="quickPrompt">Motion prompt</label><textarea id="quickPrompt" style="min-height:100px">high quality, high resolution, cinematic motion, smooth animation</textarea><div class="row"><div><label for="quickDuration">Duration</label><input id="quickDuration" type="number" min="2" max="12" step="0.1" value="3.5"></div><div style="display:flex;align-items:end"><button id="quickGenerate" type="button" class="btn" style="width:100%">Generate Scene Video</button></div></div><div id="quickStatus" class="status">Choose an image and press Generate Scene Video.</div><div id="quickResult"></div></div>
</main><script>
(function(){'use strict';
var MIN_WORDS=20,scriptEl=document.getElementById('script'),countEl=document.getElementById('count'),validationEl=document.getElementById('validation'),developBtn=document.getElementById('develop'),devStatus=document.getElementById('devStatus'),scenesEl=document.getElementById('scenes'),sceneCard=document.getElementById('sceneCard'),summaryEl=document.getElementById('summary');
var STORAGE_KEY='aiVideoScriptStudioStateV2';
function words(t){var s=String(t||'').trim();return s?s.split(/\s+/).filter(Boolean).length:0}
function esc(t){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({script:scriptEl.value,pace:document.getElementById('pace').value,minDuration:document.getElementById('minDuration').value}))}catch(e){}}
function updateCounter(){var n=words(scriptEl.value),ok=n>=MIN_WORDS;countEl.textContent=n+' words — '+(ok?'minimum reached ✓':(MIN_WORDS-n)+' more required');countEl.className='status '+(ok?'good':'bad');validationEl.className='status '+(ok?'good':'bad');validationEl.textContent=ok?'Script ready ✓. Develop Scenes is enabled.':'Please enter at least 20 words before developing scenes. Current count: '+n+'.';developBtn.disabled=!ok;if(ok)devStatus.textContent='Script ready ✓. Press Develop Scenes.';else devStatus.textContent='Type at least '+(MIN_WORDS-n)+' more word'+(MIN_WORDS-n===1?'':'s')+'.'}
scriptEl.addEventListener('input',function(){saveState();updateCounter()});scriptEl.addEventListener('change',function(){saveState();updateCounter()});scriptEl.addEventListener('keyup',function(){saveState();updateCounter()});document.getElementById('pace').addEventListener('change',saveState);document.getElementById('minDuration').addEventListener('change',saveState);window.addEventListener('beforeunload',saveState);
function splitScenes(text){var s=String(text||'').replace(/\r/g,'').trim();if(!s)return[];var blocks=s.split(/\n\s*\n+/).map(function(x){return x.trim()}).filter(Boolean);if(blocks.length>1)return blocks;var sentences=s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[s],out=[],buf='',cue=/\b(suddenly|later|meanwhile|finally|then|afterwards|after that|next morning|that night|the next day|outside|inside|near)\b/i;function flush(){if(buf.trim()){out.push(buf.trim());buf=''}}sentences.forEach(function(raw,i){var x=raw.trim();if(i>0&&cue.test(x)){flush();buf=x;return}var c=(buf?buf+' ':'')+x;if(words(c)>45){flush();buf=x}else buf=c});flush();return out.length?out:[s]}
function durationFor(t){var pace=Number(document.getElementById('pace').value)||150,min=Math.max(2,Number(document.getElementById('minDuration').value)||3);return Math.max(min,Math.min(12,Math.round((words(t)/pace*60)*2)/2))}
function motion(t){var x=t.toLowerCase(),p=[];if(/fly|flying|run|walk|move|fight|jump|swim|land|drive|ride/.test(x))p.push('natural character movement');if(/look|looks|watch|turn|face/.test(x))p.push('subtle head and eye movement');if(/wind|ocean|wave|waves|rain|cloud|storm|fire|smoke/.test(x))p.push('natural environmental motion');p.push('smooth cinematic camera movement','high quality','high resolution');return p.join(', ')}
function develop(){updateCounter();if(words(scriptEl.value)<MIN_WORDS)return;saveState();developBtn.disabled=true;devStatus.textContent='Developing scenes...';setTimeout(function(){try{var parts=splitScenes(scriptEl.value),total=0;scenesEl.innerHTML='';parts.forEach(function(part,i){var d=durationFor(part),start=total;total+=d;var c=document.createElement('div');c.className='scene';c.innerHTML='<div class="sceneHead"><b>Scene '+(i+1)+'</b><span class="badge">'+d.toFixed(1)+' sec</span></div><div class="muted" style="margin:8px 0">Timeline: '+start.toFixed(1)+'s → '+total.toFixed(1)+'s</div><div class="grid"><div><label>Scene script / narration</label><textarea class="sceneScript">'+esc(part)+'</textarea></div><div><label>Visual description</label><textarea class="sceneVisual">Cinematic visual interpretation: '+esc(part)+'</textarea></div><div><label>Motion prompt</label><textarea class="sceneMotion">'+esc(motion(part))+'</textarea></div><div><label>Scene starting image</label><input class="sceneImage" type="file" accept="image/*"><div class="sceneImageStatus status">No image selected.</div></div></div><button type="button" class="btn sceneBtn" data-index="'+i+'" '+(i?'disabled':'')+'>Generate Scene '+(i+1)+' Video</button><div class="sceneStatus status">'+(i?'Locked until previous scene succeeds.':'Ready. Choose an image.')+'</div><div class="sceneResult"></div>';scenesEl.appendChild(c)});summaryEl.textContent=parts.length+' scenes • estimated total duration '+total.toFixed(1)+' seconds';sceneCard.style.display='block';scenesEl.querySelectorAll('.sceneImage').forEach(function(inp){inp.addEventListener('change',function(){this.parentElement.querySelector('.sceneImageStatus').textContent=this.files[0]?'IMAGE LOADED ✓ '+this.files[0].name:'No image selected.'})});scenesEl.querySelectorAll('.sceneBtn').forEach(function(b){b.addEventListener('click',function(){generateScene(Number(this.dataset.index),this)})});devStatus.textContent='Scene development complete ✓';sceneCard.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){devStatus.textContent='Scene development error: '+(e?.message||e)}finally{updateCounter()}},30)}
developBtn.addEventListener('click',develop);
function restoreState(){try{var raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;var state=JSON.parse(raw)||{};if(typeof state.script==='string')scriptEl.value=state.script;if(state.pace!=null)document.getElementById('pace').value=state.pace;if(state.minDuration!=null)document.getElementById('minDuration').value=state.minDuration;updateCounter();if(words(scriptEl.value)>=MIN_WORDS)setTimeout(function(){develop()},100)}catch(e){updateCounter()}}
function extractPath(v){if(!v)return null;if(typeof v==='string'){var s=v.trim();if((s[0]==='{'||s[0]==='[')&&s.length<200000){try{return extractPath(JSON.parse(s))}catch{}}if(s.indexOf('/gradio_api/file=')>=0){var m=s.match(/https?:\/\/[^\s"']+\/gradio_api\/file=[^\s"']+|\/gradio_api\/file=[^\s"']+/);return m?m[0]:null}if(/^https?:\/\//.test(s)&&/\.(mp4|webm|mov)(\?|$)/i.test(s))return s;return null}if(Array.isArray(v)){for(var i=0;i<v.length;i++){var a=extractPath(v[i]);if(a)return a}return null}if(typeof v==='object'){for(var k in v){var b=extractPath(v[k]);if(b)return b}}return null}
function parseSSEBlock(block){var event='message',dataLines=[];block.split(/\r?\n/).forEach(function(line){if(line.indexOf('event:')===0)event=line.slice(6).trim();else if(line.indexOf('data:')===0)dataLines.push(line.slice(5).trim())});var raw=dataLines.join('\n');if(!raw)return{event:event,data:null};if(raw==='null')return{event:event,data:null};try{return{event:event,data:JSON.parse(raw)}}catch{return{event:event,data:raw}}}
async function waitForVideo(eventId,status){var r=await fetch('/api/wan/stream?eventId='+encodeURIComponent(eventId)+'&ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Wan stream HTTP '+r.status);if(!r.body)throw Error('Wan stream returned no body');var reader=r.body.getReader(),decoder=new TextDecoder(),buffer='',lastProgress='';while(true){var part=await reader.read();if(part.done)break;buffer+=decoder.decode(part.value,{stream:true});var blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()||'';for(var i=0;i<blocks.length;i++){var e=parseSSEBlock(blocks[i]);if(e.event==='error'){if(e.data===null)continue;var msg=typeof e.data==='string'?e.data:JSON.stringify(e.data);if(msg&&msg!=='null')throw Error('Wan generation error: '+msg);continue}if(e.event==='complete'||e.event==='completed'){var path=extractPath(e.data);if(path)return path;continue}if(e.data!==null){var text=typeof e.data==='string'?e.data:JSON.stringify(e.data);if(text&&text!==lastProgress){lastProgress=text;status.textContent='Wan 2.2 is generating... '+text.slice(0,180)}}}}var tail=parseSSEBlock(buffer);if(tail.event==='complete'||tail.event==='completed'){var finalPath=extractPath(tail.data);if(finalPath)return finalPath}throw Error('Wan stream ended without a video file. The job may have failed on Hugging Face.');}
async function generateScene(index,button){var cards=document.querySelectorAll('.scene'),card=cards[index],image=card.querySelector('.sceneImage').files[0],status=card.querySelector('.sceneStatus'),result=card.querySelector('.sceneResult');if(!image){status.textContent='STOPPED: choose a starting image for this scene.';return}button.disabled=true;try{var fd=new FormData();fd.append('image',image,image.name);fd.append('prompt',card.querySelector('.sceneMotion').value+' '+card.querySelector('.sceneVisual').value);fd.append('duration',String(durationFor(card.querySelector('.sceneScript').value)));status.textContent='Image loaded ✓. Sending image to Cloudflare → Hugging Face...';var r=await fetch('/api/wan/start?ts='+Date.now(),{method:'POST',body:fd,cache:'no-store'}),data=await r.json();if(!r.ok||!data.ok)throw Error(data.error||'Video request failed');status.textContent='Wan 2.2 job submitted ✓. Waiting for generation...';var path=await waitForVideo(data.eventId,status);var url='/api/wan/file?path='+encodeURIComponent(path)+'&ts='+Date.now();result.innerHTML='<video class="video" controls playsinline src="'+esc(url)+'"></video><br><a class="download" download="scene-'+(index+1)+'.mp4" href="'+esc(url)+'">Download Scene '+(index+1)+' Video</a>';status.className='sceneStatus status good';status.textContent='Scene '+(index+1)+' video generated successfully ✓ Download it now before continuing.';if(cards[index+1]){var next=cards[index+1],nb=next.querySelector('.sceneBtn');nb.disabled=false;next.querySelector('.sceneStatus').textContent='Previous scene succeeded ✓. Choose a starting image and generate this scene.';next.scrollIntoView({behavior:'smooth',block:'start'})}}catch(e){status.className='sceneStatus status bad';status.textContent='ERROR: '+(e?.message||String(e));button.disabled=false}}
var qi=document.getElementById('quickImage'),qs=document.getElementById('quickImageStatus');qi.addEventListener('change',function(){qs.textContent=this.files[0]?'IMAGE LOADED ✓ '+this.files[0].name:'No image selected.'});document.getElementById('quickGenerate').addEventListener('click',async function(){var image=qi.files[0],status=document.getElementById('quickStatus'),result=document.getElementById('quickResult'),button=this;if(!image){status.textContent='STOPPED: choose an image.';return}button.disabled=true;try{var fd=new FormData();fd.append('image',image,image.name);fd.append('prompt',document.getElementById('quickPrompt').value);fd.append('duration',document.getElementById('quickDuration').value);status.textContent='Sending image to Wan 2.2...';var r=await fetch('/api/wan/start?ts='+Date.now(),{method:'POST',body:fd,cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Video request failed');status.textContent='Wan 2.2 job submitted ✓. Waiting...';var p=await waitForVideo(d.eventId,status),u='/api/wan/file?path='+encodeURIComponent(p)+'&ts='+Date.now();result.innerHTML='<video class="video" controls playsinline src="'+esc(u)+'"></video><br><a class="download" download="scene-test.mp4" href="'+esc(u)+'">Download Video</a>';status.className='status good';status.textContent='Video generated successfully ✓'}catch(e){status.className='status bad';status.textContent='ERROR: '+(e?.message||String(e))}finally{button.disabled=false}});
updateCounter();restoreState();
})();</script></body></html>`;

export default{async fetch(request,env){const url=new URL(request.url);try{if(request.method==='POST'&&url.pathname==='/api/wan/start')return await startVideo(request,env);if(request.method==='GET'&&url.pathname==='/api/wan/stream')return await streamVideo(url.searchParams.get('eventId'),env);if(request.method==='GET'&&url.pathname==='/api/wan/file')return await videoFile(request,env);return new Response(HTML,{headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store'}})}catch(e){return json({ok:false,error:e?.message||String(e)},500)}};
