const NEGATIVE="blurry, low quality, chaotic, deformed, watermark, bad anatomy, shaky camera viewpoint";
const MIN_SCRIPT_WORDS=20;
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function base(env){const id=env.HF_SPACE||"Saravutw/WAN2.2_I2V_LIGHTNING_4-8step_custom",p=id.split("/");return "https://"+p[0].toLowerCase()+"-"+p[1].toLowerCase().replace(/[^a-z0-9]+/g,"-")+".hf.space";}
function auth(env){return env.HF_TOKEN?{Authorization:"Bearer "+env.HF_TOKEN}:{};}
async function upload(file,env){const fd=new FormData();fd.append("files",file,file.name||"input.png");const r=await fetch(base(env)+"/gradio_api/upload",{method:"POST",headers:auth(env),body:fd}),t=await r.text();if(!r.ok)throw Error("HF upload failed ("+r.status+"): "+t.slice(0,500));let x;try{x=JSON.parse(t)}catch{throw Error("HF upload returned invalid JSON")};const path=Array.isArray(x)?x[0]:x;if(!path)throw Error("HF did not return an uploaded file path");return{path,meta:{_type:"gradio.FileData"},orig_name:file.name||"input.png"};}
async function start(req,env){const f=await req.formData(),img=f.get("image");if(!(img instanceof File))return json({error:"Please choose a starting image."},400);const prompt=String(f.get("prompt")||"high quality, high resolution, cinematic motion, smooth animation"),duration=Number(f.get("duration")||3.5),image=await upload(img,env),data=[image,null,prompt,4,NEGATIVE,duration,1,1,42,true,5,"UniPCMultistep",3,16,false,true],r=await fetch(base(env)+"/gradio_api/call/generate_video",{method:"POST",headers:{...auth(env),"content-type":"application/json"},body:JSON.stringify({data})}),t=await r.text();if(!r.ok)throw Error("Wan request failed ("+r.status+"): "+t.slice(0,700));let x;try{x=JSON.parse(t)}catch{}if(!x?.event_id)throw Error("Wan did not return an event id: "+t.slice(0,700));return json({ok:true,eventId:x.event_id});}
async function stream(id,env){if(!id)return json({error:"Missing eventId"},400);const r=await fetch(base(env)+"/gradio_api/call/generate_video/"+encodeURIComponent(id),{headers:auth(env)});if(!r.ok)return new Response(await r.text(),{status:r.status,headers:{"content-type":"text/plain;charset=utf-8"}});return new Response(r.body,{headers:{"content-type":"text/event-stream;charset=utf-8","cache-control":"no-cache, no-store","connection":"keep-alive"}});}
async function proxyFile(req,env){const u=new URL(req.url),raw=u.searchParams.get("path");if(!raw)return json({error:"Missing video path"},400);let path;try{path=decodeURIComponent(raw)}catch{path=raw}if(path.startsWith("https://")){const allowed=new URL(base(env)).host;if(new URL(path).host!==allowed)return json({error:"Invalid video host"},400)}else if(!path.startsWith("/gradio_api/file="))return json({error:"Invalid video path"},400);const target=path.startsWith("https://")?path:base(env)+path,r=await fetch(target,{headers:auth(env)});if(!r.ok)return new Response(await r.text(),{status:r.status,headers:{"content-type":"text/plain;charset=utf-8"}});const h=new Headers(r.headers);h.set("cache-control","no-store");h.set("content-disposition","inline");if(!h.get("content-type")||h.get("content-type")==="application/octet-stream")h.set("content-type","video/mp4");return new Response(r.body,{status:r.status,headers:h});}
const HTML=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Cache-Control" content="no-cache"><title>AI Video Script Studio</title><style>body{font-family:system-ui;margin:0;background:#0b1020;color:#eef2ff}main{max-width:1000px;margin:auto;padding:32px 20px}h1{font-size:38px;margin:0 0 8px}.sub,.muted{color:#aeb9d6}.version{font-size:12px;color:#7f8eb5;margin:8px 0 20px}.card{background:#131b31;border:1px solid #273454;border-radius:16px;padding:20px;margin:18px 0}label{display:block;font-weight:700;margin:0 0 8px}textarea,input,select{width:100%;box-sizing:border-box;background:#0d1427;color:white;border:1px solid #344262;border-radius:10px;padding:12px;font:inherit}textarea{min-height:180px}.row,.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.scene{border:1px solid #344262;border-radius:12px;padding:14px;margin:12px 0;background:#0d1427}.sceneHead{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.sceneTitle{font-size:18px;font-weight:800}.badge{border:1px solid #47577d;border-radius:999px;padding:4px 9px;font-size:12px;color:#cbd5ff}.timeline{font-size:13px;color:#aeb9d6;margin-bottom:12px}.scene textarea{min-height:90px}.btn{background:#6d5dfc;color:white;border:0;border-radius:10px;padding:13px 18px;font-weight:800;cursor:pointer}.btn:disabled{opacity:.5;cursor:not-allowed}.secondary{background:#344262}.status{margin-top:12px;padding:12px;background:#0d1427;border-radius:10px;min-height:20px}.validationError{color:#ff5f6d;font-weight:900;display:none;margin:8px 0}.validationError.show{display:block;animation:blink 1s steps(2,start) infinite}.wordCount{margin-top:8px;font-size:14px}.bad{color:#ff5f6d;font-weight:800}.good{color:#72e6a3;font-weight:800}.preview{display:block;max-width:320px;max-height:220px;margin-top:12px;border-radius:10px}.video{max-width:100%;margin-top:15px}@media(max-width:700px){.row,.grid{grid-template-columns:1fr}}@keyframes blink{50%{opacity:.15}}</style></head><body><main><h1>AI Video Script Studio</h1><div class="sub">Script → scene development → characters → Wan 2.2 image-to-video</div><div class="version">Framework v16 • intelligent scene boundaries • Wan 2.2 generation preserved</div>
<div class="card"><label>1. Your script</label><textarea id="script" placeholder="Paste your complete story or script here."></textarea><div id="wordCount" class="wordCount bad">0 words — 20 required</div><div id="scriptValidation" class="validationError">⚠ Please enter at least 20 words before developing scenes.</div><div class="row" style="margin-top:14px"><div><label>Narration pace</label><select id="pace"><option value="130">Slow / cinematic — 130 words/min</option><option value="150" selected>Normal narration — 150 words/min</option><option value="170">Fast narration — 170 words/min</option></select></div><div><label>Minimum scene duration</label><input id="minScene" type="number" min="2" max="10" step="0.5" value="3"></div></div><p class="muted">Scene boundaries are developed locally in JavaScript. Blank lines, sentence changes, action changes, location/time cues and long sections help determine new scenes.</p><button type="button" class="btn" id="develop" onclick="developScenes()">Develop Scenes</button><div id="sceneStatus" class="status">JavaScript ready. Enter at least 20 words.</div></div>
<div class="card" id="sceneCard" style="display:none"><b>2. Developed scenes</b><div id="sceneSummary" class="muted" style="margin-top:5px"></div><div id="scenes"></div></div>
<div class="card"><label>Character workspace</label><div class="muted">Character upload / generation will be connected after scene development is stable.</div><div id="chars"></div><button type="button" class="btn secondary" onclick="addCharacter()" style="margin-top:12px">+ Add character</button></div>
<div class="card"><label>Quick scene test</label><div class="muted">Proven single-scene Wan 2.2 test.</div><div class="row"><div><label>Starting image</label><input id="image" type="file" accept="image/*"><div id="imageStatus" class="status">No image selected.</div><div id="preview"></div></div><div><label>Duration</label><input id="duration" type="number" min="2" max="10" step="0.1" value="3.5"></div></div><label style="margin-top:16px">Motion prompt</label><textarea id="prompt" style="min-height:100px">high quality, high resolution, cinematic motion, smooth animation</textarea><button type="button" class="btn" id="generate" onclick="generateSceneVideo(this)">Generate Scene Video</button><div id="status" class="status">JavaScript ready. Choose an image and press Generate Scene Video.</div><div id="result"></div></div></main>
<script>
(function(){
function countWords(t){return (String(t||'').trim().match(/\S+/g)||[]).length}
function updateCount(){var e=document.getElementById('script'),c=document.getElementById('wordCount'),v=document.getElementById('scriptValidation'),s=document.getElementById('sceneStatus');if(!e)return;var n=countWords(e.value);c.textContent=n+' words — '+(n<20?(20-n)+' more required':'minimum reached ✓');c.className='wordCount '+(n<20?'bad':'good');if(n<20){v.classList.add('show');v.textContent='⚠ Please enter at least 20 words before developing scenes. Current count: '+n+'.';s.textContent='Script too short. Add '+(20-n)+' more word'+(20-n===1?'':'s')+'.'}else{v.classList.remove('show');s.textContent='Script ready ✓ '+n+' words. Press Develop Scenes.'}}
var script=document.getElementById('script');if(script){['input','keyup','change','paste','cut','drop'].forEach(function(x){script.addEventListener(x,function(){setTimeout(updateCount,0)})});setInterval(updateCount,500);updateCount()}
window.addCharacter=function(){var n=document.querySelectorAll('.character').length+1,d=document.createElement('div');d.className='scene character';d.innerHTML='<label>Character '+n+'</label><input placeholder="Character name"><textarea style="min-height:80px;margin-top:8px" placeholder="Appearance, personality and behavior."></textarea><input type="file" accept="image/*" style="margin-top:8px">';document.getElementById('chars').appendChild(d)};
function duration(t){var p=Number(document.getElementById('pace').value)||150,m=Math.max(2,Number(document.getElementById('minScene').value)||3);return Math.max(m,Math.min(12,Math.round((countWords(t)/p*60)*2)/2))}
function splitScenes(t){var s=String(t||'').replace(/\r/g,'').trim();if(!s)return[];var blocks=s.split(/\n\s*\n+/).map(function(x){return x.trim()}).filter(Boolean);if(blocks.length>1)return blocks;var sentences=s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[s],out=[],buf='';var cue=/\b(at|inside|outside|near|from|to|into|back|away|later|meanwhile|next morning|that night|the next day|suddenly|finally|then)\b/i;var action=/\b(arrives|arrive|leaves|leave|enters|enter|returns|return|meets|meet|attacks|attack|fights|fight|speaks|says|runs|run|flies|fly|drives|drive|falls|fall|jumps|jump|opens|open|closes|close|begins|begin|starts|start|stops|stop)\b/i;function flush(){if(buf.trim()){out.push(buf.trim());buf=''}}sentences.forEach(function(raw,i){var x=raw.trim();if(!x)return;var candidate=(buf?buf+' ':'')+x;var boundary=i>0&&(cue.test(x)||(action.test(x)&&countWords(buf)>18));if(boundary||countWords(candidate)>45){flush();buf=x}else buf=candidate});flush();return out.length?out:[s]}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function fmt(x){var m=Math.floor(x/60),s=Math.round((x%60)*10)/10;return m+':'+(s<10?'0':'')+s.toFixed(1)}
function visual(t){return 'Cinematic visual interpretation: '+t}
function motion(t){var x=t.toLowerCase(),a=[];if(/fly|move|run|walk|fight|drive|ride|jump|swim/.test(x))a.push('natural character movement');if(/look|watch|turn|face|see/.test(x))a.push('subtle head and eye movement');if(/wind|ocean|rain|cloud|fire|smoke/.test(x))a.push('natural environmental motion');a.push('smooth cinematic camera movement');return a.join(', ')+', high quality, high resolution'}
window.developScenes=function(){var text=script.value.trim(),n=countWords(text),btn=document.getElementById('develop'),st=document.getElementById('sceneStatus');updateCount();if(n<20){script.focus();st.textContent='Cannot develop yet. Add '+(20-n)+' more word'+(20-n===1?'':'s')+'.';return}btn.disabled=true;st.textContent='Analyzing script and finding scene boundaries...';setTimeout(function(){try{var parts=splitScenes(text),time=0,box=document.getElementById('scenes');box.innerHTML='';parts.forEach(function(part,i){var d=duration(part),start=time;time+=d;var q=document.createElement('div');q.className='scene';q.innerHTML='<div class="sceneHead"><div class="sceneTitle">Scene '+(i+1)+'</div><span class="badge">'+d.toFixed(1)+' sec</span></div><div class="timeline">Timeline: '+fmt(start)+' → '+fmt(time)+'</div><div class="grid"><div><label>Scene script / narration</label><textarea>'+esc(part)+'</textarea></div><div><label>Visual description</label><textarea>'+esc(visual(part))+'</textarea></div><div><label>Motion prompt</label><textarea>'+esc(motion(part))+'</textarea></div><div><label>Characters / notes</label><textarea placeholder="Characters appearing in this scene."></textarea></div></div>';box.appendChild(q)});document.getElementById('sceneCard').style.display='block';document.getElementById('sceneSummary').textContent=parts.length+' scenes • estimated total duration '+fmt(time);st.textContent='Scene development complete ✓ '+parts.length+' scene'+(parts.length===1?'':'s')+' created.'}catch(e){st.textContent='Scene development error: '+e.message}btn.disabled=false;updateCount()},100)};
function setStatus(s){document.getElementById('status').textContent=s}
window.imageSelected=function(input){var f=input.files&&input.files[0],s=document.getElementById('imageStatus'),p=document.getElementById('preview');p.innerHTML='';if(!f){s.textContent='No image selected.';return}s.textContent='IMAGE LOADED ✓  '+f.name+' ('+Math.round(f.size/1024)+' KB, '+f.type+')';try{p.innerHTML='<img class="preview" src="'+URL.createObjectURL(f)+'" alt="Selected starting image">'}catch(e){}};
document.getElementById('image').addEventListener('change',function(){imageSelected(this)});
function findVideo(x){if(!x)return null;if(typeof x==='string'&&(x.indexOf('http://')===0||x.indexOf('https://')===0||x.indexOf('/gradio_api/file=')===0))return x;if(Array.isArray(x)){for(var i=0;i<x.length;i++){var u=findVideo(x[i]);if(u)return u}}if(typeof x==='object'){for(var k in x){var v=findVideo(x[k]);if(v)return v}}return null}
window.generateSceneVideo=async function(btn){setStatus('CLICK RECEIVED ✓');var file=document.getElementById('image').files&&document.getElementById('image').files[0];if(!file){setStatus('STOPPED: no starting image is loaded.');return}btn.disabled=true;document.getElementById('result').innerHTML='';try{setStatus('Image loaded ✓. Sending image to Cloudflare Worker...');var fd=new FormData();fd.append('image',file,file.name);fd.append('prompt',document.getElementById('prompt').value);fd.append('duration',document.getElementById('duration').value);var r=await fetch('/api/wan/start?nocache='+Date.now(),{method:'POST',body:fd,cache:'no-store'}),text=await r.text(),j;try{j=JSON.parse(text)}catch{throw Error('Worker returned non-JSON: '+text.slice(0,300))}if(!r.ok)throw Error(j.error||('Worker HTTP '+r.status));setStatus('Image uploaded to Hugging Face ✓. Wan 2.2 job submitted ✓. Waiting for ZeroGPU...');var q=await fetch('/api/wan/stream?eventId='+encodeURIComponent(j.eventId)+'&nocache='+Date.now(),{cache:'no-store'});if(!q.ok)throw Error('Hugging Face stream HTTP '+q.status);if(!q.body)throw Error('Browser streaming is unavailable');var reader=q.body.getReader(),dec=new TextDecoder(),buf='';while(true){var z=await reader.read();if(z.done)break;buf+=dec.decode(z.value,{stream:true});var blocks=buf.split('\n\n');buf=blocks.pop()||'';for(var bi=0;bi<blocks.length;bi++){var lines=blocks[bi].split('\n'),em='',dm='';lines.forEach(function(line){if(line.indexOf('event:')===0)em=line.slice(6).trim();if(line.indexOf('data:')===0)dm=line.slice(5).trim()});if(em==='heartbeat')continue;if(em==='generating'||em==='pending'||em==='start'){setStatus('Wan 2.2 is generating... '+dm);continue}if(em==='error')throw Error(dm||'Hugging Face returned an error');if(em==='complete'){var d;try{d=JSON.parse(dm)}catch{d=dm}var u=findVideo(d);if(!u)throw Error('Generation completed but no video file was returned.');var proxy='/api/wan/file?path='+encodeURIComponent(u),v=document.createElement('video');v.className='video';v.controls=true;v.src=proxy;v.preload='metadata';document.getElementById('result').appendChild(v);var p=document.createElement('p'),a=document.createElement('a');a.href=proxy;a.target='_blank';a.download='scene-video.mp4';a.textContent='Download generated video';p.appendChild(a);document.getElementById('result').appendChild(p);setStatus('Complete ✓ Video generated and download link is ready.');return}}}throw Error('Hugging Face closed the stream before completion')}catch(e){setStatus('Error: '+(e&&e.message?e.message:String(e)))}finally{btn.disabled=false}};
})();
</script></body></html>`;
export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname==='/api/health')return json({ok:true,version:'v16',tokenConfigured:Boolean(env.HF_TOKEN),hfSpace:env.HF_SPACE||null});if(u.pathname==='/api/wan/start'&&req.method==='POST')return await start(req,env);if(u.pathname==='/api/wan/stream'&&req.method==='GET')return await stream(u.searchParams.get('eventId'),env);if(u.pathname==='/api/wan/file'&&req.method==='GET')return await proxyFile(req,env);return new Response(HTML,{headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store, no-cache, must-revalidate','pragma':'no-cache','expires':'0','x-framework-version':'v16'}})}catch(e){return json({ok:false,error:e.message},500)}}};